foreground #eeeeee
background #00000000
cursor #eeeeee
cursor_text_color #00000000
selection_foreground #eeeeee
selection_background #242424
active_tab_foreground #eeeeee
active_tab_background #00171717
inactive_tab_foreground #292929
inactive_tab_background #00000000
color0 #00171717
color1 #ffffff
color2 #e9f3ec
color3 #f3eee9
color4 #eeeeee
color5 #eeeeee
color6 #e9f3f0
color7 #eeeeee
color8 #292929
color9 #ffffff
color10 #e9f3ec
color11 #f3eee9
color12 #eeeeee
color13 #eeeeee
color14 #e9f3f0
color15 #eeeeee
